### ISSUE TITLE
Add the ability to abort the connection if the first attempt fails.

### ISSUE THREAD

**Issue by toebes** [convergencelabs/convergence-project#178]
**Versions**
 - Convergence Version: 1.0.0-rc.7
 - OS: Windows 10
 - Browser: Chrome
 - Java Version: openjdk 12-ea 2019-03-19

**Describe the Bug**
When attempting to connect to a domain which isn't routable (in this case I am inside a firewall and the pinhole to the server doesn't seem to route correctly) the first attempt to connect to the convergence server never fails and invokes the .catch portion of the call.  In the sample code below, neither `console.log` calls are hit.

**Step To Reproduce**
1. Configure a server which can't be reached
```
Convergence.connectAnonymously("http://mydomain.com:1234/api/realtime/convergence/default")
            .then((domain: ConvergenceDomain) => {
                console.log("Success");
            })
            .catch((error) => {
                console.log("Could not connect: " + error);
            });
```
**Expected Behavior**
If the domain isn't reachable, the first attempt should fail.  Note that using the `autoreconnect: false` option from https://docs.convergence.io/js-api/interfaces/connection_and_authentication.iconvergenceoptions.html#reconnect doesn't cover the case since you want the system to continue to reconnect once the connection is established.  Ideally there should be an option like `initialreconnect: boolean` which likely should default to `false`.

**Comment by mmacfadden** [comment]
@toebes After thinking about it, there are a few issues here and a potential work around.

### The Issue
In the specific case, I haven't found a good way across browsers to detect something like a DNS error. There doesn't seem to be a unified browser API that will tell you that a connection couldn't be established due to a DNS error.  There are other errors that would equally suggest that retrying is not worth doing.  But there isn't really a good way to get a hold of them.  So it seems like either you just have to enable or disable the reconnect behavior as you mention.

### The Work Around
The `Convergence.connectAnonymously` is really a convenience method. There is another way to connect.


```JavaScript
const domain = new ConvergenceDomain("http://somehost/api/realtime/convergence/default");
domain.on(ConnectionFailedEvent.Name, () => {
  console.log("a connection attempt failed");
});

domain.on(ConnectedEvent.Name, () => {
  console.log("a connection attempt succeeded");
});

domain.connectAnonymously("displayName");
```

If you don't use the convenience method, then you have the opportunity of binding listeners to events before connecting. The convenience method is simple, but the problem is you don't get access to the domain object until the connection is made, so you can't then bind listeners to it.  So in your case:

```JavaScript
const domain = new ConvergenceDomain("http://somehost/api/realtime/convergence/default");

function connect(domain) {
  const initialConnectionListener = () => {
    console.log("a connection attempt failed");
    domain.disconnect();
    domain.on(ConnectionFailedEvent.Name, initialConnectionListener);
  };

  domain.on(ConnectionFailedEvent.Name, initialConnectionListener);

  domain.connectAnonymously("displayName");
}
```

I think this should do what you want for now.

### Enhancement
The recommended feature above seems reasonable.  It seems like the config would look like this:

```typescript
{
  reconnect { 
    autoReconnect?: boolean;
    autoReconnectOnInitial?: boolean;
    fallbackAuth?: (authChallenge: IFallbackAuthChallenge) => void; reconnectIntervals?: number[] }
  }
}
```

Where `autoReconnectInitialAttempt` would default to true for backwards compatibility.  I initially recorded this as a bug, but in retrospect I think this is just an enhancement request.
