### ISSUE TITLE
modelService.permissions(modelid).getPermissions() Promise returns undefined

### ISSUE THREAD

**Issue by toebes** [convergencelabs/convergence-project#185]
**Versions**
 - Convergence Version: 1.0.0 RC7
 - OS: Windows 10
 - Browser: Chrome

**Describe the Bug**
When handling a fulfilled ModelPermissions promise, the permissions passed is undefined.  

**Step To Reproduce**
When logged in using a JWT token, call modelService.permissions(modelid).getPermissions() on a model that exists and you have access to.  The fulfilled promise will be undefined.
```
modelService.permissions(modelid).getPermissions()
                .then((myPermissions: ModelPermissions) => {
                    if (myPermissions === undefined) {
                        console.log("Permissions is null!");
                    })

```

The problem occurs in `ModelPermissionManager.getPermissions()` which has this code:
```
 return this._connection.request(request).then((response) => {
            const { getModelPermissionsResponse } = response;
            const permissionsData = getModelPermissionsResponse.userPermissions[this._connection.session().user().username];
            return toModelPermissions(permissionsData);
```
There are actually two bugs here. 

1. `getModelPermissionsResponse` is actually an array and not a map, so when the session username (a string) is used, it will always return undefined.  The code should be iterating over the array to find the proper match.
1. In the event that nothing is found, it should be returning an empty `ModelPermissions` that has all permissions set to false.

**Expected Behavior**
A non `undefined` `ModelPermissions` should be returned as part of the Promise.

**Comment by mmacfadden** [comment]
There s a third issue here, which is that the users that are coming back are full fledged users with a type and user name, and we are only looking at the username here:

https://github.com/convergencelabs/convergence-client-javascript/blob/a7b42c894def1b92d1a9af34272ef7562bdf97b9/src/main/model/ModelMessageConverter.ts#L209

So the returned map has only the username as the key, this is wrong since it will ignore anonymous or convergence users.  We will use the above method, but must update it to account for various types of users.  This means that the keys in the map will change. While not an API change, it is a semantic change.

**Comment by mmacfadden** [comment]
I think APIs that deal with permissions will similarly need to be updated to take the user guid, instead of just the username.
