### ISSUE TITLE
Deleting users which are referenced in models, groups, or chats leaves system in a bad state

### ISSUE THREAD

**Issue by toebes** [convergencelabs/convergence-project#194]
**Versions**
 - Convergence Version: 1.0.0-rc.7
 - OS: Linux
 - Browser: chrome

**Describe the Bug**
Deleting a user which is still in use for permissions on a model leaves the model permissions in a bad state

**Step To Reproduce**
1. Create a user (I called it `AAADONOTUSE`)
1. Select any model and add that user with read permission to the model
1. Go back to the user admin and delete that user
1. Go back to the model and you see that the user name that previously said  `AAADONOTUSE` shows up as a series of somewhat random characters.  In this case it is `BbEL9za/OIz++Tiuib56MVaIKTbacJy5hlff`

Note that you can't delete that user permission (405 method not allowed, which I suspect is because of the random / in the name)

**Expected Behavior**
I would have expected that either
* You aren't allowed to delete the user which exists on permissions (preferable) or
* The user should be removed from the permissions automatically.

**Comment by mmacfadden** [comment]
I have verified this bug.  This actually applies to the entire permissions system not just the models.  Essentially what is happening now is the following.

Because several records in the database point to the user, when the user is deleted the user record is not actually removed from the database. Rather we change their username to a random set of characters and then mark them as deleted.

What we are not doing is removing them from the permissions in the system.

**Comment by mmacfadden** [comment]
This is being worked now. We have a fix implemented and it is being tested.  This will make it into 1.0.0-rc.8.

**Comment by toebes** [comment]
It would be nice if deleted users didn't show up when listing the users.  I'm fine with them staying in the database, but if you know that it is a deleted user... then just don't show it.

**Comment by mmacfadden** [comment]
The deleted user's do not show up in the system (when there are no bugs).  The issue is just that their permission records were not deleted correctly.  Once that is fixed they will not show up.  Which is what I am working on as we speak.

**Comment by toebes** [comment]
This is great to hear!
