### ISSUE TITLE
Add user level permissions for managing collections

### ISSUE THREAD

**Issue by toebes** [convergencelabs/convergence-project#201]
**Versions**
 - Convergence Version: 1.0.0-rc.7

**Description**
I find that I regularly need to set and reset the Create World Permissions for our main collection so that we don't have students accidently creating tests in our production server.  However, even when I temporarily enable it, it is possible for someone to create a test in the short window where I have it on for me to create a test.  It would be nice to have the ability to grant create permission only to specific accounts in addition to the global controls just like on any model in the collection.

A possible UI to illustrate what I am asking:
![image](https://user-images.githubusercontent.com/12609253/111672933-d3307080-87f0-11eb-9adc-b5d6b5f3675d.png)

**Is there a workaround in the absence of this feature?**
Other than manually setting/resetting the Create bit I don't see one.  The problem is that it is an all or nothing and someone else might sneak in during the time that I am creating the models.

**Comment by mmacfadden** [comment]
Interestingly.. looking here:

https://github.com/convergencelabs/convergence-server/blob/1df3523b6883fbd4ca0b78b0b36b9acaf9308872/src/main/resources/com/convergencelabs/convergence/server/db/schema/domain/schemas/1.0.yaml#L135

It seems like we have user permissions on the collections already. At least in the database. I am investigating if we are actually implementing this on the server side at all.  Since it might not require a Database change. We might be able to add this easily.

**Comment by mmacfadden** [comment]
Seems to be implemented for the most part already...

https://github.com/convergencelabs/convergence-server/blob/1df3523b6883fbd4ca0b78b0b36b9acaf9308872/src/main/scala/com/convergencelabs/convergence/server/backend/datastore/domain/model/ModelPermissionsStore.scala#L166

**Comment by mmacfadden** [comment]
Looks like we are even looking at the permissions for the collection / user when resolving permissions.

https://github.com/convergencelabs/convergence-server/blob/1df3523b6883fbd4ca0b78b0b36b9acaf9308872/src/main/scala/com/convergencelabs/convergence/server/backend/datastore/domain/model/ModelPermissionsStore.scala#L446

**Comment by mmacfadden** [comment]
We do not have a REST API for it exposed though.

https://github.com/convergencelabs/convergence-server/blob/1df3523b6883fbd4ca0b78b0b36b9acaf9308872/src/main/scala/com/convergencelabs/convergence/server/api/rest/domain/DomainCollectionService.scala#L45


My assessment is that we just need to expose a REST API for this and then add the UI, similar to what was suggested.  This should not be too hard, since most of the server side logic is already there.

**Comment by mmacfadden** [comment]
Made a bunch of progress on the server side to expose the REST API for this.

**Comment by mmacfadden** [comment]
To save space I am thinking about putting the various options in tabs.

![image](https://user-images.githubusercontent.com/1812291/117584690-fc280000-b0d3-11eb-8d1a-118caa2daedc.png)

**Comment by mmacfadden** [comment]
This has been fixed.
