### ISSUE TITLE
History API time() returning with incorrect TimeStamp

### ISSUE THREAD

**Issue by jgaspar-hiya** [convergencelabs/convergence-project#220]
**Versions**
*  Demo
   - Convergence Version: https://demos.convergence.io/code-editor/
   - OS: Linux
   - Browser: Firefox
   - Java Version: N/A
*  Reproduced in
   - Convergence Version: 1.0.0-rc.8
   - Typescript package: "@convergence/convergence": "^1.0.0-rc.8",
   - OS: Linux
   - Browser: Firefox
   - Java Version: convergencelabs/convergence-omnibus

**Describe the Bug**
HistoricalModel's time() function returns non-expected Date when using playTo (or forward / backward) to step one version at a time. See reproduction steps for more detail please.

**Step To Reproduce**
* reproduce using code
```
    let ind = 1;
    while (ind <= history.maxVersion()) {
      await history.playTo(ind)
      console.log(history.version() + "| time():  " + history.time().toLocaleString())
      ind += 1;
    }
```
```
// Output after creation (with domain.models().create(...))
1| time():  6/11/2021, 4:12:13 PM
// Output after inserting one character
1| time():  6/11/2021, 4:13:03 PM 
2| time():  6/11/2021, 4:13:03 PM
// Output after inserting two characters
1| time():  6/11/2021, 4:13:03 PM 
2| time():  6/11/2021, 4:13:03 PM 
3| time():  6/11/2021, 4:13:25 PM
```
* reproduce in the online demo-editor
  1) create a new file (leave it empty)
  2) check history (note: Version: 1 (06/11/2021 @ 2:39:10 pm) )
  3) close history, open the file and write a single letter, check history, note:
     - Version: 1 (06/11/2021 @ 2:39:50 pm)
     - Version: 2 (06/11/2021 @ 2:39:50 pm)
  3) write a new single letter, check history, note:
     - Version: 1 (06/11/2021 @ 2:39:50 pm)
     - Version: 2 (06/11/2021 @ 2:39:50 pm)
     - Version: 3 (06/11/2021 @ 2:40:35 pm)
  4) write a new single letter, check history, note:
     - Version: 1 (06/11/2021 @ 2:39:50 pm)
     - Version: 2 (06/11/2021 @ 2:39:50 pm)
     - Version: 3 (06/11/2021 @ 2:40:35 pm)
     - Version: 4 (06/11/2021 @ 2:41:10 pm)

I always dragged the slider to the far left (to version 1) and made single steps to the right.
Please note if I do the opposite the other end will get duplicated
e.g: If i go from version 4 -> version 1 it looks like the following:

    Version: 4 (06/11/2021 @ 2:41:10 pm)
    Version: 3 (06/11/2021 @ 2:41:10 pm)
    Version: 2 (06/11/2021 @ 2:40:35 pm)
    Version: 1 (06/11/2021 @ 2:39:50 pm)

It looks like to me that the timestamps are always one version “behind”.

**Expected Behavior**
When a version is selected, that version's time should be correctly associated with a model.

**Comment by mmacfadden** [comment]
@jgaspar-hiya Thanks for reporting this. I will try to replicate and investigate this weekend and report back here.

**Comment by mmacfadden** [comment]
@jgaspar-hiya I have verified the issue.  I believe this only happens when planing backwards.

Assume the following, using simplified timestamps

- Model Created: 0 Seconds
- Operation 1: 4 seconds
- Operation 2: 5 seconds
- Operation 3: 7 seconds

The model now is at version 4 and at time 7 seconds.  In general the correct versions and times are:

- v1 = 0 Seconds
- v2 = 4 Seconds
- v3 = 5 Seconds
- v4 = 7 Seconds


As you see what we actually have is the following, where operations are the bridge between versions.

```
v1 => Op 1 => v2 => Op 2 => v3 => Op 3 => v4
```

When playing back, the engine know's what operation it just played back, and sets the time and version of the model to the last operation it played back. So if you are at `v1`  and play to `v2' the engine execute `Op 2`, will set the version to 3 and the timestamp of 5 seconds (which is the timestamp of `Op 2`).

Things get trying when going backwards though. Backwards playback is achieved by inverting operations.  I will denote that as a "prime".  So the inverse of `Op 1` would be `Op 1'` for example.  In that case we have:

```
v1 <= Op 1' <= v2 <= Op 2' <= v3 <= Op 3' <= v4
```

In this case if you are at `v3`, for example, and want to play back to `v2`, what actually happens is `Op 2` is obtained and its inverse is calculated to create `Op 2'`.  `Op 2'` is then applied to the document at `v3` to arrive at `v2`.  However at that moment we are only looking at `Op 2` (really `Op 2'`, but the have the same version and timestamp).  So technically the operation we just played back say Version 3 and Time 5.  It's easy enough to realize that because we went backwards we should decrement the version by 1, to get from `3` to `2`. But since we don't have `Op 1` in hand at the moment we don't actually know what the timestamp should be.

There is actually a FIXME in the code concerning this. I added a reference to this issue.

https://github.com/convergencelabs/convergence-client-javascript/blob/17ce18bffe13115002654af6bb06ff51aa7f8603/src/main/model/historical/HistoricalModel.ts#L514


I have added this issue to the [1.0.0-rc.9](https://github.com/convergencelabs/convergence-project/milestone/8) milestone which will release by the end of June 2021.
