### ISSUE TITLE
Logging by log4j2 is not working?

### ISSUE THREAD

**Issue by hdyngd** [convergencelabs/convergence-project#83]
**Versions**
*Please fill in all that apply:*
 - Convergence Version: 1.0.0-rc.5
 - OS: CentOS Linux release 7.7.1908 (Core)

**Describe the Bug**
I try to output the convergence server logs to a file using log4j2, but it's not output.

**Step To Reproduce**
1. Set log4j2.xml as follows
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="DEBUG" shutdownHook="disable">
  <Properties>
    <Property name="filename">convergence.log</Property>
  </Properties>
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{HH:mm:ss} %-5level %logger{1} - %msg%n"/>
    </Console>
    <File name="File" fileName="${filename}">
      <PatternLayout pattern="%d{HH:mm:ss} %-5level %logger{1} - %msg%n"/>
    </File>
  </Appenders>
  <Loggers>
    <Root level="debug">
      <AppenderRef ref="Console"/>
      <AppenderRef ref="File"/>
    </Root>
    <Logger name="com.convergencelabs" level="debug" />
    <Logger name="com.orientechnologies" level="debug" />
    <Logger name="akka" level="debug" />
  </Loggers>
</Configuration>
```

2. Launch docker containers. `$ docker-compose up -d`
Since the log level is set to *debug*, something should be output to the specified file, but nothing is output.(Nothing is output even if an error occurs intentionally.)

**Expected Behavior**
A log is output to *convergence.log* in the current directory.

**Comment by mmacfadden** [comment]
@hdyngd I assume the logs are still printed to standard out if you don't add the -d flag?  I will take a look.  My initial assessment is that the docker-compose file is probably mounting the `log4j2.xml` in the wrong place within the `convergence-server` container, and thus the default log4j configuration is still being used.

**Comment by mmacfadden** [comment]
As I expected it turns out that the volume mounts were incorrect in the docker compose example. These paths changed with the recent release and were not updated.  The Convergence Server used to live at `/opt/convergence` inside the container. It now lives at `/opt/convergence-server/`. So the mounts need to be changed from:

```
    volumes:
       - ./config/convergence/log4j2.xml:/opt/convergence/conf/log4j2.xml
       - ./config/convergence/convergence-server.conf:/opt/convergence/conf/convergence-server.conf
```

to

```
    volumes:
       - ./config/convergence/log4j2.xml:/opt/convergence-server/conf/log4j2.xml
       - ./config/convergence/convergence-server.conf:/opt/convergence-server/conf/convergence-server.conf
```

This also explain an earlier issue.  The environment variables:

```
    environment:
      DB_URI: "remote:orientdb:2424"
      DB_ADMIN_USERNAME: "root"
      DB_ADMIN_PASSWORD: "password"
      CONVERGENCE_SERVER_ROLES: "backend,realtimeApi,restApi"
      CONVERGENCE_CLUSTER_SEEDS: "cluster-seed"
```

Should not have been needed. The config file located at  `config/convergence/convergence-server.conf` has those values already set.  The stock container's config doesn't and one way of setting them, in that case is the environment variables.  In the docker-compose example, we simply provide a config file with all the variables set properly.  However, the config file was also mounted to the old path and therefore was reverting back to the stock container's config.

I tested out your log4j configuration with the proper mount point, and it did behave as expected.  However, you it will not work exactly as you expect. The `convergence.log` will be created **inside** the container. Not in your working directory where you run docker-compose from. Convergence Server is running in the container and has no default access to your local file system.  If you want to get the log saved to your host file system you need to create another mount point.  Something like this:

```
    volumes:
       - ./config/convergence/log4j2.xml:/opt/convergence-server/conf/log4j2.xml
       - ./config/convergence/convergence-server.conf:/opt/convergence-server/conf/convergence-server.conf
       - ./logs:/opt/convergence-server/logs
```

This will map the local `logs` to a new `logs` inside of `/opt/convergence-server`.  Then you updated your log4j2.xml files like this to put the log in that directory:

```
<Property name="filename">logs/convergence.log</Property>
```

Now the log should appear on the host.

For reference.  In our production deployment we use things like fluentd, elasticsearch, and kibana to send all logs from all services to a centralized log database that can then be searched and visualized.

**Comment by hdyngd** [comment]
@mmacfadden Thanks for the detailed explanation. I tried it as described and it worked as expected!
Thanks for the quick response!

> For reference. In our production deployment we use things like fluentd, elasticsearch, and kibana to send all logs from all services to a centralized log database that can then be searched and visualized.

I'm very interested in this. Is there any reference document such as installation procedure? ( I'm not in a hurry about this. )

**Comment by mmacfadden** [comment]
@hdyngd We actually had this in the original docker compose configuration.  But the docker compose project was intended to get people started, and adding in all of the centralized logging stuff was making the configuration seem a bit too complex for a "getting" started. There is nothing specific to convergence i doing this.

This would be a good place to start:

https://docs.fluentd.org/container-deployment/docker-compose

We will likely do a blog post on this at some point in the future to help people get going.  If you want to try it, we'd be happy to give you some pointers in our public slack.

**Comment by hdyngd** [comment]
@

**Comment by hdyngd** [comment]
@mmacfadden Understood. It's not urgent, so I'll try it later. Thank you for the suggestion!
